# Generated by Django 4.0.4 on 2022-06-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_picture_tags_alter_category_name_delete_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='avatar_thumbnail',
        ),
    ]
