# Generated by Django 4.0.4 on 2022-06-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_picture_avatar_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='tags',
        ),
        migrations.AddField(
            model_name='picture',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photos.location'),
        ),
    ]
