# Generated by Django 4.0.4 on 2022-06-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_tags_location_remove_picture_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
